[project]
name = "huggingface-datasets-pku-posterlayout"
version = "0.1.0"
description = "A huggingface dataset for PKU Poster-Layout [Hsu+ CVPR'23]"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["datasets[vision]>=2.0.0"]

[dependency-groups]
dev = ["mypy>=1.0.0", "pytest>=6.0.0", "ruff>=0.1.5"]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
