name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Setup
        run: |
          uv sync

      - name: Format
        run: |
          uv run ruff check --output-format=github .

      - name: Lint
        run: |
          uv run ruff format --check --diff .

      - name: Type check
        run: |
          uv run mypy --cache-dir=/dev/null .

      - name: Run tests
        run: |
          uv run pytest --color=yes -rf
